"""Professional, accounting-quality report builder.

Produces multi-section reports (e.g. RECOVERIES + ADMISSIONS) in Excel, CSV and
PDF with a branded header, summary block, styled tables, alternating row
colours, frozen headers, auto-fitted columns, PKR currency formatting and a
grand total — ready to print or hand to an auditor with no extra formatting.

A "section" is:
    {"title": "RECOVERIES", "headers": [...], "rows": [[...], ...],
     "money_cols": [5, 6, 7],        # 0-based indexes formatted as PKR
     "total_col": 6}                 # optional: adds a TOTAL row
"""
from __future__ import annotations

import csv
import io
from datetime import datetime

BRAND = "BRAINS GROUP OF IT COLLEGES"
FOOTER = "Generated by Brains Group of IT Colleges Management System"

# Brand palette
_GREEN = "123D33"
_GREEN_LT = "1C5546"
_GOLD = "C9A227"
_GREY = "F2F5F3"
_WHITE = "FFFFFF"


def _fmt_date(v) -> str:
    if not v:
        return ""
    if isinstance(v, str):
        return v
    try:
        return v.strftime("%d-%m-%Y")
    except Exception:
        return str(v)


def _money(v) -> str:
    try:
        return f"Rs {float(v):,.0f}"
    except (TypeError, ValueError):
        return str(v or "")


# ────────────────────────────────────────────────────────────── CSV ──
def build_csv(title: str, meta: dict, summary: list, sections: list) -> bytes:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow([BRAND])
    w.writerow([title])
    for k, v in meta.items():
        w.writerow([k, v])
    w.writerow([])
    if summary:
        w.writerow(["SUMMARY"])
        for label, value in summary:
            w.writerow([label, value])
        w.writerow([])
    for sec in sections:
        w.writerow([sec["title"]])
        w.writerow(sec["headers"])
        for r in sec["rows"]:
            w.writerow(["" if c is None else c for c in r])
        tc = sec.get("total_col")
        if tc is not None:
            total = sum(float(r[tc] or 0) for r in sec["rows"]
                        if isinstance(r[tc], (int, float)))
            line = [""] * len(sec["headers"])
            line[max(0, tc - 1)] = "TOTAL"
            line[tc] = total
            w.writerow(line)
        w.writerow([])
    w.writerow([FOOTER])
    return buf.getvalue().encode("utf-8-sig")


# ───────────────────────────────────────────────────────────── XLSX ──
def build_xlsx(title: str, meta: dict, summary: list, sections: list) -> bytes:
    from openpyxl import Workbook
    from openpyxl.styles import (Alignment, Border, Font, PatternFill, Side)
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    ws.title = title[:31] or "Report"

    thin = Side(style="thin", color="D6DEDA")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    r = 1
    # ── Branded header
    ws.cell(r, 1, BRAND).font = Font(bold=True, size=16, color=_GREEN)
    r += 1
    ws.cell(r, 1, title).font = Font(bold=True, size=13, color=_GOLD)
    r += 1
    for k, v in meta.items():
        ws.cell(r, 1, k).font = Font(bold=True, size=9, color="5B6B64")
        ws.cell(r, 2, str(v)).font = Font(size=9)
        r += 1
    r += 1

    # ── Summary block
    if summary:
        ws.cell(r, 1, "SUMMARY").font = Font(bold=True, size=11, color=_WHITE)
        ws.cell(r, 1).fill = PatternFill("solid", fgColor=_GREEN)
        r += 1
        for label, value in summary:
            ws.cell(r, 1, label).font = Font(bold=True, size=10)
            ws.cell(r, 2, value).font = Font(size=10)
            ws.cell(r, 1).border = border
            ws.cell(r, 2).border = border
            r += 1
        r += 1

    header_rows = []
    for idx, sec in enumerate(sections):
        # Section title bar (different colour per section)
        colour = _GREEN if idx % 2 == 0 else _GREEN_LT
        ws.cell(r, 1, sec["title"]).font = Font(bold=True, size=12, color=_WHITE)
        for c in range(1, len(sec["headers"]) + 1):
            ws.cell(r, c).fill = PatternFill("solid", fgColor=colour)
        r += 1

        # Column headers
        head_row = r
        header_rows.append(head_row)
        for c, h in enumerate(sec["headers"], start=1):
            cell = ws.cell(r, c, h)
            cell.font = Font(bold=True, size=10, color=_WHITE)
            cell.fill = PatternFill("solid", fgColor=_GOLD)
            cell.alignment = Alignment(horizontal="center", vertical="center",
                                       wrap_text=True)
            cell.border = border
        r += 1

        money_cols = set(sec.get("money_cols", []))
        for i, row in enumerate(sec["rows"]):
            for c, val in enumerate(row, start=1):
                cell = ws.cell(r, c, val)
                cell.border = border
                cell.alignment = Alignment(vertical="top", wrap_text=True)
                if i % 2 == 1:                       # alternate row colour
                    cell.fill = PatternFill("solid", fgColor=_GREY)
                if (c - 1) in money_cols and isinstance(val, (int, float)):
                    cell.number_format = '"Rs" #,##0'
                    cell.alignment = Alignment(horizontal="right")
            r += 1

        # Grand total row for the section
        tc = sec.get("total_col")
        if tc is not None:
            total = sum(float(x[tc] or 0) for x in sec["rows"]
                        if isinstance(x[tc], (int, float)))
            lab = ws.cell(r, max(1, tc), "TOTAL")
            lab.font = Font(bold=True, size=11)
            val = ws.cell(r, tc + 1, total)
            val.font = Font(bold=True, size=11, color=_GREEN)
            val.number_format = '"Rs" #,##0'
            for c in range(1, len(sec["headers"]) + 1):
                ws.cell(r, c).fill = PatternFill("solid", fgColor="E7EFEA")
                ws.cell(r, c).border = border
            r += 1
        r += 2

    ws.cell(r, 1, FOOTER).font = Font(italic=True, size=9, color="93A29B")

    # Auto-fit columns
    widest = max((len(s["headers"]) for s in sections), default=1)
    for c in range(1, widest + 1):
        longest = 12
        for row in ws.iter_rows(min_col=c, max_col=c):
            for cell in row:
                if cell.value is not None:
                    longest = max(longest, min(48, len(str(cell.value)) + 3))
        ws.column_dimensions[get_column_letter(c)].width = longest

    # Freeze the first section's header row
    if header_rows:
        ws.freeze_panes = ws.cell(header_rows[0] + 1, 1)

    out = io.BytesIO()
    wb.save(out)
    return out.getvalue()


# ────────────────────────────────────────────────────────────── PDF ──
def build_pdf(title: str, meta: dict, summary: list, sections: list) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_CENTER
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (Paragraph, SimpleDocTemplate, Spacer,
                                    Table, TableStyle)

    green = colors.HexColor("#123D33")
    green_lt = colors.HexColor("#1C5546")
    gold = colors.HexColor("#C9A227")
    grey = colors.HexColor("#F2F5F3")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=12 * mm, bottomMargin=14 * mm, title=title)

    ss = getSampleStyleSheet()
    h_brand = ParagraphStyle("brand", parent=ss["Title"], fontSize=16,
                             textColor=green, spaceAfter=2, alignment=TA_CENTER)
    h_title = ParagraphStyle("t", parent=ss["Title"], fontSize=12,
                             textColor=gold, spaceAfter=6, alignment=TA_CENTER)
    meta_st = ParagraphStyle("m", parent=ss["Normal"], fontSize=8,
                             textColor=colors.HexColor("#5B6B64"),
                             alignment=TA_CENTER)
    sec_st = ParagraphStyle("s", parent=ss["Heading2"], fontSize=11,
                            textColor=colors.white, spaceBefore=2, spaceAfter=2)
    cell_st = ParagraphStyle("c", parent=ss["Normal"], fontSize=7.2, leading=9)
    head_st = ParagraphStyle("h", parent=ss["Normal"], fontSize=7.6,
                             leading=9, textColor=colors.white)

    story = [Paragraph(BRAND, h_brand), Paragraph(title, h_title)]
    if meta:
        story.append(Paragraph(
            " &nbsp;|&nbsp; ".join(f"<b>{k}:</b> {v}" for k, v in meta.items()),
            meta_st))
    story.append(Spacer(1, 7))

    if summary:
        data = [[Paragraph(f"<b>{l}</b>", cell_st), Paragraph(str(v), cell_st)]
                for l, v in summary]
        t = Table(data, colWidths=[70 * mm, 60 * mm])
        t.setStyle(TableStyle([
            ("GRID", (0, 0), (-1, -1), .4, colors.HexColor("#D6DEDA")),
            ("BACKGROUND", (0, 0), (0, -1), grey),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ]))
        story += [t, Spacer(1, 9)]

    for idx, sec in enumerate(sections):
        bar_col = green if idx % 2 == 0 else green_lt
        bar = Table([[Paragraph(sec["title"], sec_st)]],
                    colWidths=[doc.width])
        bar.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), bar_col),
            ("LEFTPADDING", (0, 0), (-1, -1), 7),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]))
        story += [bar, Spacer(1, 3)]

        money_cols = set(sec.get("money_cols", []))
        head = [Paragraph(f"<b>{h}</b>", head_st) for h in sec["headers"]]
        body = [head]
        for row in sec["rows"]:
            line = []
            for c, val in enumerate(row):
                txt = _money(val) if (c in money_cols and
                                      isinstance(val, (int, float))) else \
                    ("" if val is None else str(val))
                line.append(Paragraph(txt, cell_st))
            body.append(line)

        tc = sec.get("total_col")
        if tc is not None:
            total = sum(float(x[tc] or 0) for x in sec["rows"]
                        if isinstance(x[tc], (int, float)))
            line = [Paragraph("", cell_st)] * len(sec["headers"])
            line[max(0, tc - 1)] = Paragraph("<b>TOTAL</b>", cell_st)
            line[tc] = Paragraph(f"<b>{_money(total)}</b>", cell_st)
            body.append(line)

        n = len(sec["headers"])
        t = Table(body, colWidths=[doc.width / n] * n, repeatRows=1)
        style = [
            ("BACKGROUND", (0, 0), (-1, 0), gold),
            ("GRID", (0, 0), (-1, -1), .4, colors.HexColor("#D6DEDA")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]
        for i in range(1, len(sec["rows"]) + 1):
            if i % 2 == 0:
                style.append(("BACKGROUND", (0, i), (-1, i), grey))
        if tc is not None:
            style.append(("BACKGROUND", (0, len(body) - 1), (-1, len(body) - 1),
                          colors.HexColor("#E7EFEA")))
        t.setStyle(TableStyle(style))
        story += [t, Spacer(1, 12)]

    def _page(canvas, doc_):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(colors.HexColor("#93A29B"))
        canvas.drawString(12 * mm, 8 * mm, FOOTER)
        canvas.drawRightString(doc_.pagesize[0] - 12 * mm, 8 * mm,
                               f"Page {canvas.getPageNumber()}")
        canvas.restoreState()

    doc.build(story, onFirstPage=_page, onLaterPages=_page)
    return buf.getvalue()


def build(fmt: str, title: str, meta: dict, summary: list,
          sections: list) -> tuple[bytes, str, str]:
    """Returns (body, media_type, extension)."""
    if fmt == "csv":
        return (build_csv(title, meta, summary, sections),
                "text/csv; charset=utf-8", "csv")
    if fmt == "xlsx":
        return (build_xlsx(title, meta, summary, sections),
                "application/vnd.openxmlformats-officedocument."
                "spreadsheetml.sheet", "xlsx")
    if fmt == "pdf":
        return build_pdf(title, meta, summary, sections), "application/pdf", "pdf"
    raise ValueError("format must be csv, xlsx or pdf")


def stamp() -> str:
    return datetime.now().strftime("%d-%m-%Y %H:%M")
